name: Rust tests
# Credit: modified from github actions documentation examples

on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose
        cargo bench --verbose
        bash release.sh
        time ./target/release/non-attacking-queens -n 8 -m 8 -s
